export enum FailureCode {
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  REVERSAL_WOULD_MAKE_NEGATIVE = "REVERSAL_WOULD_MAKE_NEGATIVE",
  REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND",
  REFERENCE_NOT_PROCESSED = "REFERENCE_NOT_PROCESSED",
  INVALID_REFERENCE_KIND = "INVALID_REFERENCE_KIND",
  REFERENCE_ALREADY_REVERSED = "REFERENCE_ALREADY_REVERSED",
  AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
  CURRENCY_MISMATCH = "CURRENCY_MISMATCH",
  PLAYER_WALLET_MISMATCH = "PLAYER_WALLET_MISMATCH",
  ROUND_MISMATCH = "ROUND_MISMATCH",
  PROVIDER_MISMATCH = "PROVIDER_MISMATCH",
}

export enum WagerTransactionKind {
  Opening = "OPENING",
  Bet = "BET",
  Win = "WIN",
  Loss = "LOSS",
  Refund = "REFUND",
  Rollback = "ROLLBACK",
}

export enum WagerTransactionStatus {
  Pending = "PENDING",
  PendingReference = "PENDING_REFERENCE",
  Processed = "PROCESSED",
  Rejected = "REJECTED",
  Failed = "FAILED",
}

export enum LedgerDirection {
  Debit = "DEBIT",
  Credit = "CREDIT",
}
